# Generated by Django 2.2.7 on 2019-11-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_flower_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='slug',
        ),
    ]
